@extends('layouts.user')

@section('content')
<script src="https://cdn.tailwindcss.com"></script>
<style>
  .app-main { padding: 20px; }
</style>
<div class="tailwind-scope mt-4">
    <div class="mb-6">
        <h2 class="text-2xl font-bold text-gray-100">Global Token History</h2>
        <p class="text-gray-400">Complete ledger of all NEXA 1.0 and NEXA 2.0 generated by your account.</p>
    </div>

    <div class="bg-[#1a222d] rounded-lg shadow-lg overflow-hidden border border-[#334155]">
        <div class="px-6 py-4 border-b border-[#334155] bg-[#0f172a]">
            <h3 class="text-lg font-medium text-gray-200">Token Master Ledger</h3>
        </div>
        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-[#334155]">
                <thead class="bg-[#14172a]">
                    <tr>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Date</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Token Type</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Source</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-400 uppercase tracking-wider">Amount</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-[#334155]">
                    @forelse($history as $item)
                    <tr class="hover:bg-[#1f2937] transition-colors">
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-400">{{ \Carbon\Carbon::parse($item->created_at)->format('M d, Y h:i A') }}</td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            @if($item->token_type === 'utility')
                                <span class="bg-blue-900/30 text-blue-400 border border-blue-800 px-2 py-1 rounded-full text-xs">
                                    <i class="fa-solid fa-coins mr-1"></i>NEXA 1.0
                                </span>
                            @elseif($item->token_type === 'renewal')
                                <span class="bg-orange-900/30 text-orange-400 border border-orange-800 px-2 py-1 rounded-full text-xs">
                                    <i class="fa-solid fa-rotate mr-1"></i>NEXA 2.0
                                </span>
                            @elseif($item->token_type === 'nexa_3')
                                <span class="bg-teal-900/30 text-teal-400 border border-teal-800 px-2 py-1 rounded-full text-xs">
                                    <i class="fa-solid fa-graduation-cap mr-1"></i>NEXA 3.0
                                </span>
                            @else
                                <span class="bg-gray-800 text-gray-300 px-2 py-1 rounded-full text-xs">{{ ucfirst($item->token_type) }}</span>
                            @endif
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-300">
                            {{ $item->source ?? 'Daily ROI Generation' }}
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-bold {{ $item->token_type === 'utility' ? 'text-blue-400' : ($item->token_type === 'renewal' ? 'text-orange-400' : 'text-teal-400') }}">
                            {{ $item->token_count > 0 ? '+' : '' }}{{ number_format($item->token_count, 2) }}
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="4" class="px-6 py-10 text-center text-gray-500">
                            <i class="fa-solid fa-coins text-3xl mb-3"></i>
                            <p>No tokens recorded yet.</p>
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        <div class="px-6 py-3 border-t border-[#334155]">
            {{ $history->links() }}
        </div>
    </div>
</div>
@endsection
