<!DOCTYPE html>
<html>
<head>
    <title>Income Report</title>
    <style>
        body { font-family: sans-serif; font-size: 11px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .header { text-align: center; margin-bottom: 20px; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 9px; color: #777; }
        .amount { text-align: right; font-weight: bold; color: green; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Commission & Income Distribution Report</h1>
        <p>Generated on: {{ date('d M Y, h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Member</th>
                <th>Code</th>
                <th>Type</th>
                <th>Amount</th>
                <th>From</th>
                <th>Description</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($commissions as $item)
            <tr>
                <td>{{ $item->id }}</td>
                <td>{{ $item->user->name ?? 'N/A' }}</td>
                <td>{{ $item->user->referral_code ?? 'N/A' }}</td>
                <td>{{ ucfirst($item->commission_type) }}</td>
                <td class="amount">${{ number_format($item->amount, 2) }}</td>
                <td>{{ $item->fromUser->name ?? 'System' }}</td>
                <td>{{ $item->description }}</td>
                <td>{{ $item->created_at->format('d M Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by MLMSkill Reporting Module</p>
    </div>
</body>
</html>
